function generateQuiz(subject) {
  const bank = {
    Physics: [
      ['What is the SI unit of force?', ['Newton','Joule','Pascal','Watt'], 'Newton'],
      ['Speed of light?', ['3×10⁸ m/s','1×10⁶ m/s','3×10⁶ km/s','3×10⁵ km/s'], '3×10⁸ m/s'],
      ['Law of gravitation by?', ['Newton','Einstein','Galileo','Faraday'], 'Newton'],
      ['Unit of power?', ['Watt','Joule','Newton','Volt'], 'Watt'],
      ['Energy unit?', ['Joule','Pascal','Newton','Watt'], 'Joule'],
      ['Gravity on Earth?', ['9.8 m/s²','10','8.9','9.5'], '9.8 m/s²'],
      ['Inertia means?', ['Resistance','Speed','Force','Energy'], 'Resistance'],
      ['Vector quantity?', ['Velocity','Speed','Mass','Time'], 'Velocity'],
      ['Scalar quantity?', ['Speed','Velocity','Force','Momentum'], 'Speed'],
      ['Invented telescope?', ['Galileo','Newton','Einstein','Kepler'], 'Galileo'],
      ['Work done = ?', ['Force×displacement','Energy','Power','Time'], 'Force×displacement'],
      ['Sound travels fastest in?', ['Solid','Liquid','Gas','Vacuum'], 'Solid'],
      ['F=ma law?', ['2nd law','1st law','3rd','Gravitation'], '2nd law'],
      ['Momentum = ?', ['m×v','m+v','m/v','v/m'], 'm×v'],
      ['Pressure unit?', ['Pascal','Joule','Watt','Newton'], 'Pascal'],
      ['Charge unit?', ['Coulomb','Volt','Ampere','Ohm'], 'Coulomb'],
      ['Current unit?', ['Ampere','Volt','Ohm','Coulomb'], 'Ampere'],
      ['Potential difference unit?', ['Volt','Ohm','Joule','Ampere'], 'Volt'],
      ['1 HP = ?', ['746 W','1000 W','500 W','960 W'], '746 W'],
      ['X-rays discovered by?', ['Roentgen','Newton','Einstein','Maxwell'], 'Roentgen']
    ],
    Chemistry: [
      ['Chemical symbol of gold?', ['Au','Ag','Gd','Pb'], 'Au'],
      ['Water formula?', ['H₂O','CO₂','O₂','NaCl'], 'H₂O'],
      ['Atomic number of oxygen?', ['8','16','12','6'], '8'],
      ['Common salt formula?', ['NaCl','KCl','HCl','Na₂CO₃'], 'NaCl'],
      ['pH of neutral solution?', ['7','1','10','14'], '7'],
      ['Vinegar contains?', ['Acetic acid','Citric acid','Sulphuric acid','Nitric acid'], 'Acetic acid'],
      ['NaOH called?', ['Caustic soda','Baking soda','Washing soda','Bleaching powder'], 'Caustic soda'],
      ['H₂SO₄ known as?', ['Sulphuric acid','Nitric acid','Hydrochloric acid','Acetic acid'], 'Sulphuric acid'],
      ['CO₂ used in?', ['Fire extinguishers','Cooking','Batteries','Fertilizers'], 'Fire extinguishers'],
      ['Alcohol formula?', ['C₂H₅OH','CH₄','C₆H₆','H₂O'], 'C₂H₅OH'],
      ['Gas in soft drinks?', ['CO₂','O₂','N₂','H₂'], 'CO₂'],
      ['Periodic table founder?', ['Mendeleev','Newton','Einstein','Rutherford'], 'Mendeleev'],
      ['Most abundant gas in air?', ['Nitrogen','Oxygen','Carbon dioxide','Argon'], 'Nitrogen'],
      ['Bleaching powder formula?', ['CaOCl₂','NaCl','KCl','CaCO₃'], 'CaOCl₂'],
      ['Rust formula?', ['Fe₂O₃','FeO','Fe₃O₄','FeS'], 'Fe₂O₃'],
      ['Hydrogen symbol?', ['H','Hy','He','Hu'], 'H'],
      ['Atomic number of carbon?', ['6','8','10','12'], '6'],
      ['Ammonia formula?', ['NH₃','NO₂','HNO₃','N₂'], 'NH₃'],
      ['Gas for respiration?', ['Oxygen','CO₂','Nitrogen','Helium'], 'Oxygen'],
      ['Acid turns blue litmus?', ['Red','Blue','No change','Yellow'], 'Red']
    ],
    Maths: [
      ['Value of π?', ['3.14','2.17','3.41','3.21'], '3.14'],
      ['Square root of 81?', ['9','8','7','6'], '9'],
      ['Perimeter of square = ?', ['4×side','2×side','side²','side³'], '4×side'],
      ['Area of circle = ?', ['πr²','2πr','πd','r²'], 'πr²'],
      ['100 ÷ 4 = ?', ['25','20','15','30'], '25'],
      ['15% of 200 = ?', ['30','20','25','35'], '30'],
      ['LCM of 4 and 6?', ['12','24','8','10'], '12'],
      ['Cube of 5?', ['125','25','15','150'], '125'],
      ['Solve: 2x+4=10, x=?', ['3','2','4','5'], '3'],
      ['Perimeter of rectangle = ?', ['2(l+b)','l×b','4b','l+b'], '2(l+b)'],
      ['7×6 = ?', ['42','36','48','40'], '42'],
      ['Sin(90°)=?', ['1','0','0.5','2'], '1'],
      ['Cos(0°)=?', ['1','0','-1','2'], '1'],
      ['Log(1)=?', ['0','1','∞','-1'], '0'],
      ['Derivative of x²?', ['2x','x','x²','2'], '2x'],
      ['Integration of 1/x?', ['ln|x|','x²/2','1/x²','x'], 'ln|x|'],
      ['10³=?', ['1000','100','10','10000'], '1000'],
      ['Smallest prime number?', ['2','1','3','0'], '2'],
      ['Angle sum of triangle?', ['180°','90°','270°','360°'], '180°'],
      ['Mean of 2,4,6,8,10?', ['6','5','4','7'], '6']
    ],
    Science: [
      ['Humans breathe in?', ['Oxygen','Carbon dioxide','Nitrogen','Helium'], 'Oxygen'],
      ['Photosynthesis uses?', ['CO₂ + H₂O','O₂ + H₂O','N₂ + H₂O','CO₂ + O₂'], 'CO₂ + H₂O'],
      ['Largest organ in human body?', ['Skin','Heart','Liver','Lungs'], 'Skin'],
      ['Blood is pumped by?', ['Heart','Lungs','Kidney','Brain'], 'Heart'],
      ['Planet closest to Sun?', ['Mercury','Venus','Earth','Mars'], 'Mercury'],
      ['Water freezes at?', ['0°C','100°C','32°C','50°C'], '0°C'],
      ['Boiling point of water?', ['100°C','50°C','80°C','120°C'], '100°C'],
      ['Human skeleton bones?', ['206','208','210','205'], '206'],
      ['Process of water cycle?', ['Evaporation','Sublimation','Fusion','Condensation'], 'Evaporation'],
      ['Sun is a?', ['Star','Planet','Comet','Asteroid'], 'Star'],
      ['Plants release oxygen?', ['Day','Night','Always','Never'], 'Day'],
      ['Earth revolves around?', ['Sun','Moon','Mars','Jupiter'], 'Sun'],
      ['Insects have how many legs?', ['6','4','8','10'], '6'],
      ['Part of plant doing photosynthesis?', ['Leaf','Root','Stem','Flower'], 'Leaf'],
      ['Brain is protected by?', ['Skull','Rib cage','Spine','Skin'], 'Skull'],
      ['Heart beats per minute?', ['72','60','80','100'], '72'],
      ['Gas essential for burning?', ['Oxygen','Hydrogen','Nitrogen','CO₂'], 'Oxygen'],
      ['Nucleus controls?', ['Cell','Tissue','Organ','Organism'], 'Cell'],
      ['Mammals feed babies with?', ['Milk','Water','Blood','Juice'], 'Milk'],
      ['Fish breathe using?', ['Gills','Lungs','Skin','Mouth'], 'Gills']
    ],
    English: [
      ['Synonym of "Happy"?', ['Joyful','Sad','Angry','Tired'], 'Joyful'],
      ['Antonym of "Big"?', ['Small','Large','Huge','Tall'], 'Small'],
      ['Plural of "Child"?', ['Children','Childs','Childes','Childer'], 'Children'],
      ['Past tense of "Go"?', ['Went','Gone','Going','Goes'], 'Went'],
      ['Verb in "He eats apple"?', ['Eats','He','Apple','None'], 'Eats'],
      ['Noun in "The boy runs"?', ['Boy','Runs','The','None'], 'Boy'],
      ['Adjective in "Tall tree"?', ['Tall','Tree','A','Is'], 'Tall'],
      ['Opposite of "Hot"?', ['Cold','Warm','Cool','Soft'], 'Cold'],
      ['Word starting with vowel?', ['Apple','Boy','Dog','Cat'], 'Apple'],
      ['Past of "See"?', ['Saw','Seen','Sees','Seeing'], 'Saw'],
      ['Pronoun of "Ravi"?', ['He','She','It','They'], 'He'],
      ['Article in "An orange"?', ['An','A','The','None'], 'An'],
      ['Word for group of lions?', ['Pride','Herd','Pack','Crowd'], 'Pride'],
      ['Preposition in "On the table"?', ['On','Table','The','None'], 'On'],
      ['Opposite of "Fast"?', ['Slow','Quick','Rapid','Swift'], 'Slow'],
      ['Rhyming word of "Cat"?', ['Hat','Dog','Cow','Hen'], 'Hat'],
      ['"I" is a?', ['Pronoun','Verb','Adjective','Noun'], 'Pronoun'],
      ['Adverb in "He runs quickly"?', ['Quickly','He','Runs','None'], 'Quickly'],
      ['Word meaning "Opposite"?', ['Antonym','Synonym','Homonym','Adjective'], 'Antonym'],
      ['Plural of "Book"?', ['Books','Bookes','Bookies','Booky'], 'Books']
    ],
    Hindi: [
      ['"जल" का अर्थ क्या है?', ['पानी','हवा','अग्नि','मिट्टी'], 'पानी'],
      ['"माँ" का विलोम?', ['पिता','बेटा','भाई','बहन'], 'पिता'],
      ['"सुंदर" का समानार्थी?', ['खूबसूरत','बदसूरत','छोटा','बड़ा'], 'खूबसूरत'],
      ['"दिन" का विलोम?', ['रात','सुबह','शाम','भोर'], 'रात'],
      ['"खाना" का अर्थ?', ['भोजन','कपड़ा','पानी','आसमान'], 'भोजन'],
      ['"राम" कौन है?', ['मनुष्य','देवता','पशु','राजा'], 'देवता'],
      ['"विद्यालय" का अर्थ?', ['स्कूल','मंदिर','घर','दुकान'], 'स्कूल'],
      ['"नदी" का अर्थ?', ['जलधारा','पर्वत','गांव','पेड़'], 'जलधारा'],
      ['"काला" का विलोम?', ['सफेद','लाल','हरा','नीला'], 'सफेद'],
      ['"पक्षी" कहाँ उड़ता है?', ['आसमान','पानी','धरती','समुद्र'], 'आसमान'],
      ['"गाय" देती है?', ['दूध','पानी','भोजन','फल'], 'दूध'],
      ['"पेड़" से क्या मिलता है?', ['छाया','धूप','धूल','हवा'], 'छाया'],
      ['"सूरज" किस दिशा में उगता है?', ['पूर्व','पश्चिम','उत्तर','दक्षिण'], 'पूर्व'],
      ['"फल" का विलोम?', ['सब्जी','बीज','खाली','फूल'], 'सब्जी'],
      ['"भोजन" किससे मिलता है?', ['कृषक','मजदूर','डॉक्टर','शिक्षक'], 'कृषक'],
      ['"कमल" क्या है?', ['फूल','पक्षी','फल','पेड़'], 'फूल'],
      ['"आकाश" का रंग?', ['नीला','लाल','हरा','सफेद'], 'नीला'],
      ['"पानी" कहाँ से आता है?', ['बादल','सूरज','हवा','पेड़'], 'बादल'],
      ['"बिल्ली" क्या खाती है?', ['दूध','फल','रोटी','पानी'], 'दूध'],
      ['"किताब" कहाँ पढ़ी जाती है?', ['विद्यालय','बाजार','घर','खेत'], 'विद्यालय']
    ],
    "General Knowledge": [
      ['Capital of India?', ['New Delhi','Mumbai','Kolkata','Chennai'], 'New Delhi'],
      ['National animal of India?', ['Tiger','Lion','Elephant','Cow'], 'Tiger'],
      ['National bird?', ['Peacock','Crow','Sparrow','Parrot'], 'Peacock'],
      ['Currency of India?', ['Rupee','Dollar','Euro','Yen'], 'Rupee'],
      ['Current PM of India (2025)?', ['Narendra Modi','Rahul Gandhi','Amit Shah','Manmohan Singh'], 'Narendra Modi'],
      ['Who wrote National Anthem?', ['Rabindranath Tagore','Gandhi','Tilak','Subhash Bose'], 'Rabindranath Tagore'],
      ['First President of India?', ['Dr. Rajendra Prasad','Nehru','Patel','Indira Gandhi'], 'Dr. Rajendra Prasad'],
      ['Longest river in India?', ['Ganga','Yamuna','Brahmaputra','Narmada'], 'Ganga'],
      ['Largest planet?', ['Jupiter','Earth','Saturn','Mars'], 'Jupiter'],
      ['Smallest continent?', ['Australia','Asia','Europe','Africa'], 'Australia'],
      ['Taj Mahal built by?', ['Shah Jahan','Akbar','Aurangzeb','Babar'], 'Shah Jahan'],
      ['National flower of India?', ['Lotus','Rose','Lily','Jasmine'], 'Lotus'],
      ['Which festival is of lights?', ['Diwali','Holi','Eid','Navratri'], 'Diwali'],
      ['Cricket played with?', ['Bat & Ball','Stick','Racket','Net'], 'Bat & Ball'],
      ['Largest ocean?', ['Pacific','Atlantic','Indian','Arctic'], 'Pacific'],
      ['Who discovered gravity?', ['Newton','Einstein','Galileo','Faraday'], 'Newton'],
      ['Largest desert?', ['Sahara','Thar','Gobi','Kalahari'], 'Sahara'],
      ['How many colors in rainbow?', ['7','5','8','6'], '7'],
      ['National game of India?', ['Hockey','Cricket','Kabaddi','Football'], 'Hockey'],
      ['Fastest animal?', ['Cheetah','Horse','Lion','Tiger'], 'Cheetah']
    ]
  };

  const questions = bank[subject] || bank.Physics; // fallback
  const quizDiv = document.getElementById('quizContainer');
  quizDiv.innerHTML = '';
  questions.forEach((q, i) => {
    const div = document.createElement('div');
    div.className = 'question';
    div.innerHTML = `<p><strong>Q${i + 1}:</strong> ${q[0]}</p>` +
      q[1].map(o => `<label><input type='radio' name='q${i}' value='${o}'> ${o}</label>`).join('');
    quizDiv.appendChild(div);
  });
  quizDiv.dataset.questions = JSON.stringify(questions);
}
